name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'fuzz/**'
      - '.clusterfuzzlite/**'
      - '.github/workflows/cflite_pr.yml'

permissions: read-all

jobs:
  fuzz:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-address-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Harden runner (audit)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      - name: Build Rust fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: rust
          sanitizer: address
      - name: Run affected fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          fuzz-seconds: 120
          mode: code-change
          sanitizer: address
          output-sarif: true
